### ISSUE TITLE
Non-existing template engine gives DI error

### ISSUE THREAD

**Issue by c410-f3r** [FriendsOfSymfony/FOSRestBundle#1652]
Since [this PR](https://github.com/symfony/symfony/pull/19120), templating can be disabled with the following configuration:

```
framework:
    templating: false
```
 
Using this causes the following error to arise:

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]          
Unable to replace alias "fos_rest.templating" with actual definition "templating". 

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
You have requested a non-existent service "templating".
```

**Comment by GuilhemN** [comment]
I thought https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1655 fixed this but in fact it does not, we can't easily fix it as the `ViewHandler` depends on the Templating component and we would need to adapt it to make it work without it.
Feel free to submit a PR if you're willing to do it :)

**Comment by sogetimaitral** [comment]
Hello,

New user here (on both symfony and FOS Rest Bundle).
Should I understand that we need to keep and get twig running to be able to run FOS Rest Bundle?
We wanted to disable it to avoid using it, since we only want a REST API using JSON only...
Thanks for the help.

**Comment by xabbuh** [comment]
We should solve the issue somehow. But we need to deeper think about a proper solution.

**Comment by c410-f3r** [comment]
@GuilhemN Thanks for the initiative for trying to fix the problem. I would like the send a PR but right now I don't have time and I don't know how FOSRestBundle works, maybe in the near future.
@sogetimaitral Twig is useful for development when using the web profiler.

**Comment by sogetimaitral** [comment]
Interesting, Twig is used by the profiler front-end. I note that, thanks for the hint :)

**Comment by GuilhemN** [comment]
see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1675

**Comment by c410-f3r** [comment]
Used the same configuration with latest commit (66b66dd5f2589f4c4453a1734f0e765aa3502fc0) and the problem still persist.

Tried several configurations:

```
framework:
    templating: false
```

```
framework:
    templating:
        enabled: false
```

```
framework:
    templating:
        enabled: false
        engines: []
```

```
framework:
    templating:
        enabled: false
        engines: ['php']
```

**Comment by GuilhemN** [comment]
@c410-f3r https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1684 should be the last fix...
